hyosung-final-team2/final-project

ubun2_fe/src/customer/components/Login/LandingIntro.jsx, ubun2_fe/src/customer/components/common/Input/InputText.jsx, ubun2_fe/src/customer/pages/external/Login.jsx
* 로그인 페이지 
* 로그인 페이지 구현
* InputText 공통컴포넌트에 추가로 들어가면 좋을 것 같은 속성 확인해주세요.
=> KAN-17 feat:로그인 페이지

ubun2_fe/src/customer/components/Register/RegisterCompletion.jsx, ubun2_fe/src/customer/components/Register/RegisterFirstStep.jsx, ubun2_fe/src/customer/components/Register/RegisterSecondStep.jsx, ubun2_fe/src/customer/components/Register/RegisterStepBar.jsx, ubun2_fe/src/customer/components/Register/RegisterThirdStep.jsx, ubun2_fe/src/customer/components/common/Input/InputTextWithBtn.jsx, ubun2_fe/src/customer/pages/external/Register.jsx, ubun2_fe/src/customer/store/Register/registerStepStore.js
* 고객 회원가입 페이지 UI 
* 고객 회원가입 페이지 및 API통한 것 제외한 프론트 단에서의 기본적 validation
* 공통 컴포넌트에서 추가적으로 들어가면 좋을 것 같은 속성
=> KAN-40 feat:고객 회원가입 페이지

ubun2_be/build.gradle, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/entity/Customer.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/exception/CustomerException.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/exception/CustomerExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/CustomerService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/config/S3Config.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductDeleteRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/entity/Product.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/exception/category/CategoryException.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/exception/category/CategoryExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/exception/image/ImageException.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/exception/image/ImageExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/exception/product/ProductException.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/exception/product/ProductExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/CategoryRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/CategoryService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ImageService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/CategoryServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ImageServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java
* 상품 기능 구현
* 상품 목록
* 상품 상세
* 상품 등록, 수정, 삭제
* 상품 등록시 validation 기준 생각해보기
=> Kan 25 feature/back product

ubun2_fe/src/customer/components/common/Table/TableBody.jsx, ubun2_fe/src/customer/components/common/Table/TableHead.jsx
체크박스가 없는 Table 컴포넌트에서도 재사용이 가능하게 isCheckable props를 추가했습니다.
* Checkbox가 없는 컴포넌트에서 Table 컴포넌트 재사용이 불가능합니다.
* Checkbox가 존재하지 않는 컴포넌트에서도 Table을 재사용 가능하게 props를 추가했습니다.
* props 사용이 적절했는지 봐주세요.
=> feat: TableBody, TableHead 변경

ubun2_fe/src/customer/components/common/Dropdown/Dropdown.jsx, ubun2_fe/src/customer/components/common/Dropdown/SearchableDropdown.jsx, ubun2_fe/src/customer/components/common/Input/InfoInput.jsx, ubun2_fe/src/customer/components/common/Input/InputLabel.jsx, ubun2_fe/src/customer/components/common/Input/MemberInfo.jsx, ubun2_fe/src/customer/components/common/Input/SearchInput.jsx
* 주소 목록 테이블에 필요한 공통 컴포넌트
* 주소 목록 테이블에 필요한 공통 컴포넌트들을 추가했습니다.
=> feat: 주문 목록 테이블 관련 공통 컴포넌트 생성

ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberInsertModal/AddressInfoSection/AddressInfoSection.jsx, ubun2_fe/src/customer/components/MemberList/MemberInsertModal/MemberInsertModal.jsx, ubun2_fe/src/customer/components/MemberList/MemberInsertModal/PaymentInfoSection/PaymentInfoSection.jsx, ubun2_fe/src/customer/components/MemberList/MemberInsertModal/PaymentInfoSection/PaymentRegisterTable.jsx, ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentTable/MemberPaymentTable.jsx, ubun2_fe/src/customer/components/common/Info/MemberInfo.jsx, ubun2_fe/src/customer/components/common/Input/AddressInput.jsx, ubun2_fe/src/customer/components/common/Input/PaymentInput.jsx
=> KAN-66 feature/front member insert modal

ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressEditModal.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTable.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTableRow.jsx, ubun2_fe/src/customer/components/MemberList/MemberInsertModal/AddressInfoSection/AddressInfoSection.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTableFeature.jsx, ubun2_fe/src/customer/components/common/Input/AddressInput.jsx, ubun2_fe/src/customer/store/Address/useAddressStore.js
* 주소 수정 모달 구현
* 주소 수정 모달 구현
* 모달위에 모달이 아닌 갈아끼우는 방식으로 변경
=> Kan 67 feature/front member address edit modal

ubun2_be/build.gradle, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/filter/LoginFilter.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/utils/JwtUtil.java
* JwtUtil, 로그인 성공에 따른 AccessToken 발급 로직
* JwtUtil, 로그인 성공에 따른 AccessToken 발급 로직
*
=> Kan 68 feature/back jwt

ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressListData.js, ubun2_fe/src/customer/components/common/Dropdown/Dropdown.jsx
*  버튼 통일성 유지를 위한 스타일링 & 더미데이터 코드 정리
*  버튼 통일성 유지를 위한 스타일링 & 더미데이터 코드 정리
=> KAN-31 feature/front address table

ubun2_fe/src/customer/components/StoreInfo/StoreDescriptionNotice.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoData.js, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDetail.jsx, ubun2_fe/src/customer/components/common/Input/InputLabel.jsx, ubun2_fe/src/customer/components/common/Input/UpdateInputLabel.jsx, ubun2_fe/src/customer/pages/internal/StoreInfo.jsx
* 고객의 상점 정보 페이지를 구현
* 고객의 상점 정보 페이지를 구현
* 추후 API 를 통해 데이터 전달 구현 예정입니다.
=> Kan-59 feat : 고객 상점 정보 구현

ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx, ubun2_fe/src/customer/components/MemberList/ExcelModal/ExcelModal.jsx, ubun2_fe/src/customer/components/MemberList/ExcelModal/ExcelUploadResult.jsx, ubun2_fe/src/customer/components/MemberList/ExcelModal/ImportFileInfo.jsx, ubun2_fe/src/customer/components/MemberList/ExcelModal/InputExcelFile.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailModal.jsx, ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx
* 고객 회원 기능 엑셀 등록하는 모달 구현 
* 고객 회원 기능 엑셀 등록하는 모달 구현
*
=> KAN-43 feat: 고객 엑셀 등록 모달

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/impl/AddressRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/TestSecurityConfig.java
* address.getMember().get을 하면 쿼리가 N+1번 조회되기 때문에 조회성능을 고려해서 QueryDsl 을 사용
* QueryDsl 사용
* 
=> KAN-72-feature/back find all address

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductDeleteRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/entity/Category.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImplTest.java
* 상품 서비스 테스트 코드 작성
* 상품 서비스 테스트 코드
* 테스트 코드 작성법에 대해서 피드백 받고싶습니다.
=> Kan 25 feature/dev product

ubun2_be/build.gradle, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/config/MailConfig.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/EmailAuthenticationRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/EmailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/EmailService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/EmailServiceImpl.java
* 인증번호 이메일 발송 및 인증번호 검증
* 인증번호 발송
* 인증번호 검증
*
=> KAN 81 feature/back member

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressDto.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressMemberDetailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressMemberInfoResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressResponseDto.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/exception/AddressExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/exception/address/AddressException.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/exception/address/AddressExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/impl/AddressRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressControllerTest.java
* 주소를 통해 회원 상세조회 기능 구현
* 주소를 통해 회원 상세조회 기능 구현
*
=> Kan 82 feature/back 주소로 회원정보 조회

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/EmailService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/controller/EmailController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/EmailAuthenticationRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/EmailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/EmailService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/EmailServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/config/CorsMvcConfig.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/config/RedisConfig.java
=> KAN-81 refactor: 패키지 구조 변경

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressMemberInfoResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressControllerTest.java
* 회원 주소 등록기능 구현
* 회원 주소 등록기능을 구현하고 테스트를 실행합니다.
*
=> Kan 73 feature/back find member address info

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/UnifiedOrderResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/Order.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/OrderProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/SubscriptionOrderProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerControllerTest.java
* 단건 주문 상세 조회 기능 구현
* 단건 주문 상세 조회 기능 구현
*
=> Kan-77-feat : 단건 주문 상세 조회

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/AccountPayment/AccountPaymentRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/AccountPayment/AccountPaymentResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/CardPayment/CardPaymentRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/CardPayment/CardPaymentResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/MemberPaymentMethodsResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodDetailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/AccountPayment.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/CardPayment.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/exception/paymentMethod/PaymentMethodException.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/exception/paymentMethod/PaymentMethodExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/impl/PaymentMethodRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodControllerTest.java
* 고객 결제수단 관련 기능 개발
* 고객 결제수단 관련 기능 추가
* 커스텀 예외 추가
=> Kan 85 feature/back payment method

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderDetailProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/OrderProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/SubscriptionOrderProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/exception/OrderExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java
* 정기 주문 상세 조회 기능 구현
* 정기 주문 상세 조회 기능 구현
* 테스트는 추후에 작성하겠습니다 🥲
=> Kan-78 feat : 정기 주문 상세 조회

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/response/MemberListResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/PendingMemberRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java, ubun2_fe/src/App.jsx, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/memberTable.js, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/queris.js, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableRow.jsx, ubun2_fe/src/customer/components/common/Pagination/TablePagination.jsx, ubun2_fe/src/customer/components/common/Table/DynamicTableBody.jsx, ubun2_fe/src/customer/components/common/Table/TableBody.jsx, ubun2_fe/src/customer/pages/external/Login.jsx, ubun2_fe/src/customer/store/Modal/modalStatusStore.js
* 전체 회원 리스트 API 연동, React-Query pre-fetch 사용한 UX 개선
- API 스펙에 맞게 TableBody를 id와 key를 props로 받을 수 있는 DynamicTableBody로 변경
*
=> Kan 84 feature/front api

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressMemberInfoResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/MemberDetailAddressResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/entity/Address.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/impl/AddressRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java
* 고객의 주소관련 기능 전체적인 수정
* customerId를 체크하는 로직으로 전체 변경
* repository는 entity를 반환하게 수정
=> Kan 71 feature/back address

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderApproveRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionApproveRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/Order.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/OrderProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/exception/OrderExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java
* 단기 주문 승인 / 취소 구현
* 단기 주문 승인 / 취소 구현
*
=> Kan-79 feat : 단기 주문 승인 / 취소

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderApproveRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionApproveRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/SubscriptionOrder.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/SubscriptionOrderProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java
* 정기 주문 승인 / 취소 기능 구현
* 정기 주문 승인 / 취소 기능 구현
*
=> Kan-80 feat : 정기 주문 승인 / 취소 처리

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/SignupRequest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/CustomerControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/TestUserDetailsService.java
* customer controller 테스트 코드
*
*
=> KAN-89 test: customer controller TestCode

ubun2_be/build.gradle, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/SmsController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/SmsRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/provider/SmsProvider.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/SmsService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/SmsServiceImpl.java, ubun2_fe/package-lock.json, ubun2_fe/package.json, ubun2_fe/src/customer/components/Calendar/CalendarIndex.jsx, ubun2_fe/src/customer/components/Calendar/CalendarView.jsx, ubun2_fe/src/customer/components/Calendar/dummy.js, ubun2_fe/src/customer/components/Calendar/util.js, ubun2_fe/src/customer/components/Dashboard/DashboardIndex.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/AmountStats.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardStats.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardTopBar.jsx, ubun2_fe/src/customer/pages/internal/Dashboard.jsx
=> Kan 96 feature/back sms

ubun2_fe/src/customer/components/Calendar/CalendarIndex.jsx, ubun2_fe/src/customer/components/Calendar/CalendarView.jsx, ubun2_fe/src/customer/components/Calendar/dummy.js, ubun2_fe/src/customer/components/Calendar/util.js
* FE 캘린더 UI 및 데이터셋 결정 
*
* 더 필요하거나 있으면 좋을 것 같은 거 있으면 얘기해주세요
=> KAN-93 feat: 캘린더 UI & response 데이터

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/SmsController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/provider/SmsProvider.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/SmsService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/SmsServiceImpl.java, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/memberTable.js, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/queris.js, ubun2_fe/src/customer/components/MemberList/MemberRegisterModal/MemberRegisterModal.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableFeature.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableRow.jsx, ubun2_fe/src/customer/components/common/Table/DynamicTableBody.jsx
=> Kan 97 fe api feature/front sms

ubun2_fe/src/customer/api/Calendar/calendar.js, ubun2_fe/src/customer/api/Calendar/queris.js, ubun2_fe/src/customer/components/Calendar/CalendarView.jsx
=> KAN-99 feat: calendar 조회 API 연동

ubun2_fe/src/customer/components/Calendar/CalendarIndex.jsx, ubun2_fe/src/customer/components/Calendar/CalendarView.jsx
=> KAN-99 feat: 캘린더 api 연동

ubun2_fe/src/customer/components/AddressList/AddressTableRow.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx, ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx, ubun2_fe/src/customer/components/common/Modal/ConfirmationModal.jsx
* 테이블 헤더 수정 & 하드코딩 수정
* 테이블 헤더 수정 & 하드코딩 수정
=> KAN-86 chore: 테이블 헤더 수정 & 하드코딩 수정

ubun2_fe/src/customer/components/common/Dropdown/Dropdown.jsx, ubun2_fe/src/customer/components/common/Modal/ConfirmationModal.jsx, ubun2_fe/src/customer/components/common/Modal/icons.jsx, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx
* 확인 모달 컴포넌트화 & 드롭다운이 페이지 이동 직후 클릭 시 작동하지 않던 버그를 수정
* 모달 컴포넌트화 & 버그 수정
=> Kan 86 feature/front address

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java, ubun2_fe/src/customer/api/Customer/MemberList/MemberModal/queris.js, ubun2_fe/src/customer/api/Register/queris.js, ubun2_fe/src/customer/components/Calendar/CalendarView.jsx, ubun2_fe/src/customer/components/MemberList/MemberRegisterModal/MemberRegisterModal.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/Register/RegisterSecondStep.jsx, ubun2_fe/src/customer/components/common/Input/InputTextWithBtn.jsx, ubun2_fe/src/customer/components/common/Regex/registerRegex.js
=> Kan 100 feature/front registerapi

ubun2_fe/src/member/components/Product/ProductItem.jsx, ubun2_fe/src/member/components/StoreList/StoreListItem.jsx, ubun2_fe/src/member/layouts/FootNav.jsx, ubun2_fe/src/member/layouts/FootNavItem.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/layouts/MemHeader.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/external/ForgotPassword.jsx, ubun2_fe/src/member/pages/external/Login.jsx, ubun2_fe/src/member/pages/external/Register.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/MyPage.jsx, ubun2_fe/src/member/pages/internal/Product.jsx, ubun2_fe/src/member/pages/internal/Store.jsx, ubun2_fe/src/member/pages/internal/StoreList.jsx, ubun2_fe/src/member/store/currentLocationStore.js, ubun2_fe/src/member/store/memberStore.js, ubun2_fe/src/member/store/storeStore.js
=> KAN-102 feat: member mobile layout

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/common/entity/BaseTimeEntity.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/CustomerResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/entity/Member.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/entity/Product.java, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductInfo.jsx, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductSaleInfo.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx, ubun2_fe/src/customer/components/common/Table/TableBody.jsx
* 등록된 상점조회 기능
* 등록된 상점 목록 조회
*
=> Kan 103 feature/back member

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/entity/Address.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/AccountPayment.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/CardPayment.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java
* 삭제 기능 status 관리 수정
* 삭제 기능 status 관리 수정
=> Kan 20 feature/back address

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductMemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/CategoryResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/CategoryRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/CategoryService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/CategoryServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java
* 카테고리, 상품 조회 기능 구현
* 카테고리 조회
* 상품 목록 조회
* 상품 상세 조회
*
=> Kan 130 feature/back member product

ubun2_fe/src/member/components/common/SlideUpModal.jsx, ubun2_fe/src/member/components/common/button/BottomButton.jsx
* 공통 모달&버튼 컴포넌트 구현
* 공통으로 쓸 모달과 버튼
*
=> KAN-109 feat: 공통 버튼&하단 모달 컴포넌트 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/AccountPayment.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/CardPayment.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java
* request 객체 controller -> service
* controller 책임 수정
*
=> KAN-82 chore: request 객체 controller -> service & 쓰지않는 Import 제거

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/controller/FindInfoController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/FindIdRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/FindIdResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/FindInfoService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/FindInfoServiceImpl.java
=> KAN-132 feat: 아이디 찾기 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/entity/Customer.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/entity/Member.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/controller/FindInfoController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/ResetPasswordRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/exception/AuthExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/FindInfoService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/FindInfoServiceImpl.java
=> KAN-134 feat: 비밀번호 재설정

ubun2_fe/src/index.css, ubun2_fe/src/member/components/Cart/cartDummyData.js, ubun2_fe/src/member/components/Cart/cartList/CartCardCustom.js, ubun2_fe/src/member/components/Cart/cartList/CartSingleOrder.jsx, ubun2_fe/src/member/components/Cart/cartList/CartStore.jsx, ubun2_fe/src/member/components/Cart/cartList/CartSubscriptionOrder.jsx, ubun2_fe/src/member/components/common/SlideUpModal.jsx, ubun2_fe/src/member/components/common/button/QuantityButton.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryCompleted.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryPre.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemEditable.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemReadOnly.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/store/modalStore.js
* 회원 장바구니 페이지 구현
* 회원 장바구니 페이지 구현
*
=> Kan-113 feat : 회원 장바구니 페이지 구현

ubun2_fe/src/customer/api/common/Login/queris.js, ubun2_fe/src/customer/components/common/Input/InputText.jsx, ubun2_fe/src/customer/pages/external/Login.jsx, ubun2_fe/src/member/components/common/button/BottomButton.jsx, ubun2_fe/src/member/components/common/button/CustomButton.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/external/ForgotPassword.jsx, ubun2_fe/src/member/pages/external/Login.jsx, ubun2_fe/tailwind.config.js
* 회원 로그인 처리 & API 연동
*
- 클라이언트 화면 테스트 완료 
*
=> KAN-128 feat: 회원 로그인 처리

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/exception/AuthExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/EmailServiceImpl.java, ubun2_fe/src/App.jsx, ubun2_fe/src/customer/api/common/Login/queris.js, ubun2_fe/src/customer/components/common/Input/InputTextWithBtn.jsx, ubun2_fe/src/member/api/FindInfo/findInfo.js, ubun2_fe/src/member/api/FindInfo/queris.js, ubun2_fe/src/member/components/ForgotLoginId/FindLoginResult.jsx, ubun2_fe/src/member/components/common/button/DoubleBottomButton.jsx, ubun2_fe/src/member/pages/external/ForgotLoginId.jsx, ubun2_fe/src/member/pages/external/Login.jsx
=> KAN-135 feat: 프론트 아이디 찾기 UI & API 연동

ubun2_fe/src/App.jsx, ubun2_fe/src/member/api/FindInfo/findInfo.js, ubun2_fe/src/member/api/FindInfo/queris.js, ubun2_fe/src/member/pages/external/ForgotLoginId.jsx, ubun2_fe/src/member/pages/external/ForgotPassword.jsx, ubun2_fe/src/member/pages/external/ResetPassword.jsx
=> KAN-136 feat: 회원 비밀번호 찾기 UI & API 연동

ubun2_fe/src/member/api/FindInfo/findInfo.js, ubun2_fe/src/member/api/FindInfo/queris.js, ubun2_fe/src/member/components/ForgotLoginId/FindLoginResult.jsx, ubun2_fe/src/member/components/Register/RegisterSecondStep.jsx, ubun2_fe/src/member/pages/external/ForgotPassword.jsx, ubun2_fe/src/member/pages/external/ResetPassword.jsx
* 회원의 비밀번호 재설정 UI & API 연동
*
*
=> KAN-137 feat : 회원 비밀번호 재설정 UI & API 연동

ubun2_fe/src/member/components/Order/Order/OrderDeliveryInfo.jsx, ubun2_fe/src/member/components/Order/Order/OrderStore.jsx, ubun2_fe/src/member/components/Order/Order/SingleOrder.jsx, ubun2_fe/src/member/components/Order/Order/SubscriptionOrder.jsx, ubun2_fe/src/member/components/Order/OrderModal/AddressModalContent.jsx, ubun2_fe/src/member/components/Order/OrderModal/DeliveryModalContent.jsx, ubun2_fe/src/member/components/Order/orderDummyData.js, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryPre.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemReadOnly.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/Order.jsx
* 회원 주문 페이지 UI 구현
* 회원 주문 페이지 UI 구현
*
=> Kan-120 feat : 회원 주문 페이지 UI 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java, ubun2_fe/package-lock.json, ubun2_fe/package.json, ubun2_fe/src/member/api/Store/queris.js, ubun2_fe/src/member/api/Store/store.js, ubun2_fe/src/member/components/StoreList/StoreListItem.jsx, ubun2_fe/src/member/layouts/MemHeader.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/Product.jsx, ubun2_fe/src/member/pages/internal/Store.jsx, ubun2_fe/src/member/pages/internal/StoreList.jsx, ubun2_fe/src/member/store/storeStore.js
=> Kan 139 fe feature/front store

ubun2_fe/package.json, ubun2_fe/src/customer/api/addressApi.js, ubun2_fe/src/customer/components/common/Dropdown/Dropdown.jsx, ubun2_fe/src/member/api/addressApi.js, ubun2_fe/src/member/components/common/input/InfoInput.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/ChooseAddress.jsx, ubun2_fe/src/member/pages/internal/ChoosePayment.jsx, ubun2_fe/src/member/pages/internal/MyPaymentsList.jsx, ubun2_fe/src/member/pages/internal/RegisterAddress.jsx, ubun2_fe/src/member/store/address/AddressStore.js, ubun2_fe/tailwind.config.js
* 디바이스 크기에 따른 소소한 스타일 변경 및 모바일 확인용 Host를 dev2로 오픈합니다.
*
*
=> Kan 110 chore/front member

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/MemberAddressController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/exception/AddressExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MyAddressResponse.java
* 회원의 주소지 관련 기능 api 구현 (주소지 조회,수정,추가,삭제 구현 완료)
* 회원의 주소지 관련 기능 api 구현
*
=> KAN-147 feat: 회원의 주소지 관련 기능 api 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/AnnouncementResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_fe/src/member/api/Store/queris.js, ubun2_fe/src/member/api/Store/store.js, ubun2_fe/src/member/components/StoreList/Announcement.jsx, ubun2_fe/src/member/pages/internal/Store.jsx, ubun2_fe/src/member/store/storeStore.js
* 상점 공지사항 모달, 공지사항 API, 상점 내 스크롤 위치 상태 관리, 최초 입장 시에만 공지사항 open
*
*
=> Kan 142 feature/front announcement

ubun2_fe/src/member/components/Cart/cartDummyData.js, ubun2_fe/src/member/components/Cart/cartList/CartSingleOrder.jsx, ubun2_fe/src/member/components/Cart/cartList/CartStore.jsx, ubun2_fe/src/member/components/Cart/cartList/CartSubscriptionOrder.jsx, ubun2_fe/src/member/components/Order/Order/OrderDeliveryInfo.jsx, ubun2_fe/src/member/components/Order/Order/OrderStore.jsx, ubun2_fe/src/member/components/Order/Order/SingleOrder.jsx, ubun2_fe/src/member/components/Order/Order/SubscriptionOrder.jsx, ubun2_fe/src/member/components/OrderComplete/OrderCompleteStore.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryCompleted.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemEditable.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemReadOnly.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/Order.jsx, ubun2_fe/src/member/pages/internal/OrderComplete.jsx, ubun2_fe/src/member/store/order/orderItemStore.js
* 회원 주문 완료 UI 구현
* 회원 주문 완료 UI 구현
*
=> Kan-122 feat : 회원 주문 완료 UI 구현

ubun2_fe/src/assets/images/single-line.svg, ubun2_fe/src/assets/images/subscription-line.svg, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/MyPage.jsx, ubun2_fe/src/member/pages/internal/OrderComplete.jsx
* mypage 메인 메뉴 UI 구현
* mypage 메인 메뉴 UI 구현
*
=> Kan-123 feat : mypage 메인 메뉴 UI 구현

ubun2_fe/src/member/components/Cart/cartDummyData.js, ubun2_fe/src/member/components/Order/orderDummyData.js, ubun2_fe/src/member/components/common/badge/OrderStatusBadge.jsx, ubun2_fe/src/member/components/common/badge/OrderStatusTextBadge.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryCompleted.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemReadOnly.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/MyOrdersList.jsx, ubun2_fe/src/member/pages/internal/MySingleOrderDetail.jsx
* 마이페이지 단건 주문 상세 UI 구현
* 마이페이지 단건 주문 상세 UI 구현
*
=> Kan-125 feat : 마이페이지 단건 주문 상세 UI 구현

ubun2_fe/src/index.css, ubun2_fe/src/member/components/Product/ProductItem.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/Store.jsx, ubun2_fe/src/member/pages/internal/StoreList.jsx
=> KAN-155 feat: 상품 전체 리스트 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/entity/Address.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MyAddressResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepository.java, ubun2_fe/src/customer/api/Address/AddressModal/queris.js, ubun2_fe/src/customer/api/Address/AddressTable/queris.js, ubun2_fe/src/member/api/Address/addresses.js, ubun2_fe/src/member/api/Address/queries.js, ubun2_fe/src/member/components/Address/AddressItem.jsx, ubun2_fe/src/member/components/Address/AddressSearchMobilePopUp.jsx, ubun2_fe/src/member/components/common/button/BottomButton.jsx, ubun2_fe/src/member/pages/internal/ChooseAddress.jsx, ubun2_fe/src/member/pages/internal/RegisterAddress.jsx, ubun2_fe/src/member/store/address/AddressStore.js
* 주소지 조회, 등록, 수정, 삭제 api 연동
* 주소지 조회, 등록, 수정, 삭제 api 연동
*
=> Kan 150 feature/front member address api

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/controller/CartController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/entity/Cart.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/entity/CartProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/exception/CartException.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/exception/CartExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/CartService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/impl/CartServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java
* 회원 장바구니 추가 및 등록 기능 구현
* 회원 장바구니 추가 및 등록 기능 구현
*
=> Kan-164 feat : 회원 장바구니 추가 기능 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/MemberPaymentMethodController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/AccountPayment/MyAccountPaymentResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/CardPayment/MyCardPaymentResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/entity/PaymentMethod.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java, ubun2_fe/src/member/api/Address/queries.js, ubun2_fe/src/member/api/Payment/payments.js, ubun2_fe/src/member/api/Payment/queries.js, ubun2_fe/src/member/components/PaymentMethod/AccountForm.jsx, ubun2_fe/src/member/components/PaymentMethod/CardForm.jsx, ubun2_fe/src/member/components/PaymentMethod/CardList.jsx, ubun2_fe/src/member/components/PaymentMethod/CreditCard.jsx, ubun2_fe/src/member/components/PaymentMethod/PaymentItem.jsx, ubun2_fe/src/member/components/common/input/FloatingLabelInput.jsx, ubun2_fe/src/member/components/common/input/InfoInput.jsx, ubun2_fe/src/member/pages/internal/ChoosePayment.jsx, ubun2_fe/src/member/pages/internal/EditPayment.jsx, ubun2_fe/src/member/pages/internal/RegisterAddress.jsx, ubun2_fe/src/member/store/Payment/PaymentStore.js
* 결제수단 조회 & 등록 api 연동 구현
* 결제수단 조회 & 등록 api 연동 구현
*
=> Kan 151 feature/front member payment api

ubun2_fe/src/member/api/Store/queris.js, ubun2_fe/src/member/components/Product/ProductItem.jsx, ubun2_fe/src/member/components/Product/SelectOrderTypeModal.jsx, ubun2_fe/src/member/components/Product/SelectQuantityModal.jsx, ubun2_fe/src/member/components/StoreList/StoreListItem.jsx, ubun2_fe/src/member/components/common/SlideUpModal.jsx, ubun2_fe/src/member/components/common/accordion/AccordionBody.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/Product.jsx, ubun2_fe/src/member/pages/internal/Store.jsx, ubun2_fe/src/member/pages/internal/StoreList.jsx
* 상품 상세 페이지, react-query 상품상세 prefetch & 쿼리 최적화 
*
*
=> Kan 141 fe feature/front category

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/controller/CartController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductDeleteRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductDetailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductUpdateRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/entity/CartProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/exception/CartExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartProductRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/CartService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/impl/CartServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/entity/Product.java
* 회원 장바구니 기능 구현
* 회원 장바구니 기능 구현
*
=> Kan-163 feat : 회원 장바구니 기능 구현

ubun2_fe/src/member/api/Store/queris.js, ubun2_fe/src/member/api/Store/store.js, ubun2_fe/src/member/components/Product/SelectCategoryModal.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/Store.jsx
=> KAN-141 feat: category modal

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/CartService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/impl/CartServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderMemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/CancelOrderRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/RemoveSubscriptionOrderProductRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/UnifiedOrderResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/Order.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/entity/OrderProduct.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderProductRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/SubscriptionOrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/SubscriptionOrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/InventoryService.java
* 회원 주문 관련 API 기능 구현
* 회원 주문 관련 API 기능 구현
*
=> Kan-156 feat : 회원 주문 관련 API 기능 구현

ubun2_be/.gitignore, ubun2_be/build.gradle, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/config/FirebaseConfig.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/FcmMessage.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/GroupAlarmSendRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/PersonalAlarmSendRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/FcmTokenRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MemberSignUpRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/entity/Member.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberCustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java, ubun2_fe/public/firebase-messaging-sw.js, ubun2_fe/src/FCMTokenStore.js, ubun2_fe/src/customer/api/common/Login/queris.js, ubun2_fe/src/member/api/FcmToken/fcmToken.js, ubun2_fe/src/member/api/FcmToken/queris.js, ubun2_fe/src/member/api/Register/queris.js, ubun2_fe/src/member/pages/internal/StoreList.jsx
=> Kan 179 feature/back pushnotification

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/entity/Alarm.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/repository/AlarmRedisRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberCustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java
* 레디스 회원별 알림 저장 / 알림 읽음 처리
*
*
=> Kan 182 feature/back alarmsave

ubun2_fe/src/member/api/Cart/queris.js, ubun2_fe/src/member/api/Order/order.js, ubun2_fe/src/member/api/Order/queris.js, ubun2_fe/src/member/components/Cart/cartDummyData.js, ubun2_fe/src/member/components/Order/Order/OrderDeliveryInfo.jsx, ubun2_fe/src/member/components/Order/OrderModal/AddressModalContent.jsx, ubun2_fe/src/member/components/Order/OrderModal/DeliveryModalContent.jsx, ubun2_fe/src/member/pages/external/Login.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/Order.jsx, ubun2_fe/src/member/store/order/orderItemStore.js
* 주문 등록 API 연동
* 현재 주문 등록에 필요한 카드, 배송지 정보는 같이 연결하면서 진행해야할 것 같습니다!
*
=> Kan-173 주문 등록 API 연동

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java
* security config, controller end-point 변경 
*
*
=> KAN-182 chore: config 변경

ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx, ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentTable/MemberPaymentTableRow.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentInfo.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodAccount.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodCard.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTable.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTableRow.jsx, ubun2_fe/src/customer/utils/cardFormat.js, ubun2_fe/src/member/components/PaymentMethod/Account.jsx, ubun2_fe/src/member/components/PaymentMethod/AccountForm.jsx, ubun2_fe/src/member/components/PaymentMethod/CardList.jsx, ubun2_fe/src/member/components/PaymentMethod/CreditCard.jsx
* 회원 계좌 결제수단 UI 변경 & 고객 계좌 결제수단 UI 변경
* 회원 계좌 결제수단 UI 변경 & 고객 계좌 결제수단 UI 변경
*
=> Kan 186 feature/front payment UI

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/AddressesResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/MemberCountResponseDto.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/OrderCountResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/OrderSummaryResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/ProductCountResponseDto.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/TopSellingProductDto.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/UnifiedOrderResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/DashboardService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/impl/DashboardServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberCustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/PendingMemberRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepository.java
* 대시보드 통계와 관련된 백엔드 api 구현
* 대시보드 통계와 관련된 백엔드 api 구현
*
=> Kan 187 feature/back dashboard api

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/repository/CustomerAlarmRedisRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/repository/MemberAlarmRedisRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/CustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/SignupRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/entity/Customer.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/CustomerService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/SubscriptionOrderServiceImpl.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/CustomerControllerTest.java, ubun2_fe/src/customer/api/Customer/Register/queris.js, ubun2_fe/src/customer/api/common/Login/queris.js, ubun2_fe/src/member/api/FcmToken/fcmToken.js, ubun2_fe/src/member/pages/internal/RegisterAddress.jsx
=> Kan 192 feature/back pushtocustomer

ubun2_fe/src/member/api/Cart/queris.js, ubun2_fe/src/member/api/Order/queris.js, ubun2_fe/src/member/api/toastStyle.js, ubun2_fe/src/member/pages/internal/Product.jsx
* 공통 toast style 정의
* 공통 toast style 정의
*
=> KAN-166 style: 공통 toast 스타일 정의

ubun2_fe/package.json
* package json 누락
* package json 누락
=> KAN-194 chore: package.json 업로드

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_fe/src/App.jsx, ubun2_fe/src/customer/api/notification/notification.js, ubun2_fe/src/customer/api/notification/queris.js, ubun2_fe/src/customer/components/Notification/NotificationItem.jsx, ubun2_fe/src/customer/components/Notification/NotificationList.jsx, ubun2_fe/src/customer/layouts/Header.jsx, ubun2_fe/src/customer/layouts/Layout.jsx, ubun2_fe/src/customer/layouts/RightSideBar.jsx, ubun2_fe/src/customer/store/Notification/notificationStore.js
* 고객 대시보드 알림 사이드바 & API 연동
*
*
=> Kan 193 feature/front customeralarm

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/SubscriptionOrderServiceImpl.java
* 정기주문 생성 알림, 연기 알림, 재고부족 알림
*
*
=> Kan 199 feature/back subscription push

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/OrderProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/OrderSummaryResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/SubscriptionOrderProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/UnifiedOrderResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/DashboardService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/impl/DashboardServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_fe/src/customer/components/Dashboard/DashboardAreaChart.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardIndex.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashBoardLineChart.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardPieChart.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardStats.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardTopBar.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrders.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrdersTableRow.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/SidoMap.jsx, ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodAccount.jsx, ubun2_fe/src/member/store/address/AddressStore.js, ubun2_fe/tailwind.config.js
=> Kan 198 feature/front dashboard api

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/DashboardService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/impl/DashboardServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_fe/src/customer/components/Dashboard/DashboardIndex.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardTopBar.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrders.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/UnifiedOrdersTableBody.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/SidoMap.jsx
* dashboard 데이터 받는 방식 변경
* dashboard 데이터 받는 방식 변경 member와 비교 대신 product에서 customerId 비교
*
=> Kan 187 refactor/dashboard

ubun2_fe/src/member/components/Cart/cartList/EmptyCartBox.jsx, ubun2_fe/src/member/components/Order/Order/OrderDeliveryInfo.jsx, ubun2_fe/src/member/components/Product/SelectQuantityModal.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryCompleted.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryPre.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemEditable.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemReadOnly.jsx, ubun2_fe/src/member/components/common/productItem/SubscriptionProductItemEditable.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/ChoosePayment.jsx, ubun2_fe/src/member/pages/internal/InputPassword.jsx, ubun2_fe/src/member/pages/internal/MyOrdersList.jsx, ubun2_fe/src/member/pages/internal/MyPage.jsx, ubun2_fe/src/member/pages/internal/MySingleOrderDetail.jsx, ubun2_fe/src/member/pages/internal/MySubscriptionOrderDetail.jsx, ubun2_fe/src/member/pages/internal/Order.jsx, ubun2_fe/src/member/pages/internal/OrderComplete.jsx, ubun2_fe/src/member/pages/internal/Product.jsx, ubun2_fe/src/member/store/order/orderItemStore.js
* UI 카트, 주문 목록 수정
* UI 카트, 주문 목록 수정
*
=> Kan 172 feature/front member order

ubun2_fe/package-lock.json, ubun2_fe/src/customer/api/Dashboard/dashboard.js, ubun2_fe/src/customer/api/Dashboard/queries.js, ubun2_fe/src/customer/components/Dashboard/DashboardItem/SidoMap.jsx, ubun2_fe/tailwind.config.js
* dashboard api useQuery
* dashboard api useQuery
*
=> KAN-198 feat: dashboard api useQuery

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/PendingMemberRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/SubscriptionOrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/enums/PaymentMethodOption.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/PaymentMethodRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/impl/PaymentMethodRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepositoryImpl.java
=> Kan 197 feature/back search

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductMemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/CategoryRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java
* 카테고리별 상품 출력 기능 구현
* 카테고리별 상품 출력 기능 구현
*
=> Kan 201 feature/back category

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/PaymentPasswordRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/exception/member/MemberExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java
=> KAN-202 feat: 간편결제 비밀번호 체크

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MemberInfoResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_fe/src/customer/api/common/Login/login.js, ubun2_fe/src/customer/api/common/Login/queris.js, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductInfo.jsx, ubun2_fe/src/customer/components/common/Dropdown/Dropdown.jsx, ubun2_fe/src/member/store/memberStore.js
=> Kan 203 feature/back memberinfo

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java, ubun2_fe/src/customer/api/Product/ProductList/ProductInsertModal/productInsertModal.js, ubun2_fe/src/customer/api/Product/ProductList/ProductInsertModal/queris.js, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductCategory.jsx
* 전체 카테고리 조회 / front API 연동
*
*
=> Kan 204 feature/back category

ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductCategory.jsx, ubun2_fe/src/member/api/Store/store.js, ubun2_fe/src/member/components/Product/ProductItem.jsx, ubun2_fe/src/member/components/Product/SelectCategoryModal.jsx, ubun2_fe/src/member/components/StoreList/StoreListItem.jsx, ubun2_fe/src/member/pages/internal/Product.jsx, ubun2_fe/src/member/pages/internal/Store.jsx, ubun2_fe/src/member/store/category/categoryStore.js
=> KAN-206 feat: 회원의 카테고리별 상품 조회 API 연동

.github/workflows/fe_deploy.yml, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductCategory.jsx, ubun2_fe/src/member/api/Store/store.js, ubun2_fe/src/member/components/Product/ProductItem.jsx, ubun2_fe/src/member/components/Product/SelectCategoryModal.jsx, ubun2_fe/src/member/components/StoreList/StoreListItem.jsx, ubun2_fe/src/member/pages/internal/Product.jsx, ubun2_fe/src/member/pages/internal/Store.jsx, ubun2_fe/src/member/store/category/categoryStore.js
=> 2차 배포 설정 수정

ubun2_fe/src/customer/api/Address/AddressTable/addressTable.js, ubun2_fe/src/member/api/Address/addresses.js, ubun2_fe/src/member/components/PaymentMethod/CreditCard.jsx, ubun2_fe/src/member/components/common/SlideUpModal.jsx, ubun2_fe/src/member/components/common/button/BottomButton.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/pages/internal/ChooseAddress.jsx, ubun2_fe/src/member/pages/internal/ChoosePayment.jsx, ubun2_fe/src/member/pages/internal/EditPayment.jsx, ubun2_fe/src/member/pages/internal/RegisterAddress.jsx
* dvw -> % & BottomButton 수정
*
*
=> KAN-194 feat:UI 수정 dvw -> % & BottomButton 수정

ubun2_fe/package-lock.json, ubun2_fe/package.json, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/memberTable.js, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/queris.js, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableFeature.jsx, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx, ubun2_fe/src/customer/components/common/Table/TableHead.jsx, ubun2_fe/src/customer/components/common/Table/TableHeadCell.jsx, ubun2_fe/src/customer/components/common/Table/tableIndex.js, ubun2_fe/src/customer/store/MemberTable/memberTableStore.js
* 고객의 회원테이블 검색 & 정렬 API 연동
*
*
=> KAN-207 feat: 고객의 회원테이블 검색 & 정렬 API 연동

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/entity/Member.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/MemberService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_fe/src/member/api/Payment/payments.js, ubun2_fe/src/member/api/Payment/queries.js, ubun2_fe/src/member/components/PaymentMethod/PasswordKeypad.jsx, ubun2_fe/src/member/layouts/PageContent.jsx, ubun2_fe/src/member/pages/internal/InputPassword.jsx, ubun2_fe/src/member/pages/internal/MyPaymentsList.jsx, ubun2_fe/src/member/store/Payment/PaymentStore.js
* dashboard controller uri에 api추가
* dashboard 간편결제 비밀번호 연동
*
*
=> Kan 198 feat/front dashboard api

ubun2_fe/src/member/components/PaymentMethod/SetPasswordKeypad.jsx, ubun2_fe/src/member/pages/internal/SetPassword.jsx
* 결제 비밀번호 ui 구현
* 결제 비밀번호 ui 구현
*
=> KAN-198 feat: 결제비밀번호 ui

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/GroupAlarmSendRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/dto/PersonalAlarmSendRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/entity/Alarm.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_fe/src/customer/api/notification/queris.js, ubun2_fe/src/customer/layouts/Header.jsx, ubun2_fe/src/member/components/notification/Notification.jsx, ubun2_fe/src/member/components/notification/NotificationItem.jsx, ubun2_fe/src/member/layouts/Layout.jsx, ubun2_fe/src/member/layouts/MemHeader.jsx, ubun2_fe/src/member/layouts/PageContent.jsx
=> Kan 208 feature/back pushlink

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/DeleteSelectedProductRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductInsertlModal.jsx
* 상품 리스트 삭제 기능 구현
* 상품 리스트 삭제 DTO 생성
* 상품 리스트 삭제 기능 구현
*
=> KAN-209 feat: 상품 리스트 삭제 기능 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/CustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/MemberDeleteRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/CustomerService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/entity/Member.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/DeleteSelectedProductRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductInsertlModal.jsx, ubun2_fe/src/customer/components/Register/RegisterSecondStep.jsx
* 회원 리스트 삭제 기능 구현
* 회원 리스트 삭제 dto 생성
* 회원 리스트 삭제 기능 구현
*
=> Kan 211 feature/back member

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/dto/AddressDeleteRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/AddressService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/service/impl/AddressServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductDeleteSelectedRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java
=> Kan 213 feature/back address

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/address/repository/impl/AddressRepositoryImpl.java, ubun2_fe/src/customer/api/Address/AddressModal/addressModal.js, ubun2_fe/src/customer/api/Address/AddressModal/queris.js, ubun2_fe/src/customer/api/Address/AddressTable/addressTable.js, ubun2_fe/src/customer/api/Address/AddressTable/queris.js, ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressModal.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressMap.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTableRow.jsx, ubun2_fe/src/customer/components/common/Input/AddressInput.jsx, ubun2_fe/src/customer/components/common/Table/tableIndex.js, ubun2_fe/src/customer/store/Address/addressTableStore.js, ubun2_fe/src/customer/store/Address/useAddressStore.js, ubun2_fe/src/member/pages/internal/RegisterAddress.jsx
* 주소 상세 modal 변경 & 고객단 주소목록 검색 & 정렬 기능 구현
* 주소 상세 modal 변경 & 고객단 주소목록 검색 & 정렬 기능 구현
*
=> Kan 200 refactor/front dashboard

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/PaymentMethodDeleteRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/PaymentMethodService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java
=> KAN-214 feat: 결제수단 리스트 삭제

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/CustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/MyPageUpdateRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/entity/Customer.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/CustomerService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java
* 고객 마이페이지 수정기능 구현
* 고객 마이페이지 수정 dto 생성
* 고객 마이페이지 수정기능 구현
*
=> KAN-215 feat: 고객 마이페이지 수정기능 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/controller/CartController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductDeleteRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductDetailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/dto/CartProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartProductRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/repository/CartRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/CartService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/impl/CartServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderMemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_fe/src/member/api/Cart/queris.js, ubun2_fe/src/member/api/Order/order.js, ubun2_fe/src/member/api/Order/queris.js, ubun2_fe/src/member/components/Cart/cartList/CartStore.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/InputPassword.jsx, ubun2_fe/src/member/pages/internal/MySubscriptionOrderDetail.jsx, ubun2_fe/src/member/store/order/orderItemStore.js
* 카트 및 주문 로직 수정
* 카트 및 주문 로직 수정
*
=> Kan-205 refactor : cart - order fix

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_fe/src/customer/components/Notification/NotificationItem.jsx
* 주문 정렬,검색 기능 구현
* 주문 정렬,검색 기능 구현
*
=> KAN-216 feat: 주문 정렬,검색 기능 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderMemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/SubscriptionOrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/SubscriptionOrderServiceImpl.java
=> KAN-156 refactor:회원 정기 주문 유효성 검사 로직 분리

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/UnifiedOrderResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java
=> Kan-22 refactor : 고객 주문 관련 수정

ubun2_fe/src/customer/components/ForgotLoginId/FindLoginId.jsx, ubun2_fe/src/customer/components/ForgotPassword/FindPassword.jsx, ubun2_fe/src/customer/components/ForgotPassword/ResetPassword.jsx, ubun2_fe/src/customer/components/Register/RegisterFirstStep.jsx, ubun2_fe/src/customer/components/Register/RegisterSecondStep.jsx, ubun2_fe/src/customer/components/Register/RegisterThirdStep.jsx, ubun2_fe/src/customer/components/common/Input/InputText.jsx, ubun2_fe/src/customer/components/common/Input/InputTextWithBtn.jsx, ubun2_fe/src/customer/components/common/Regex/registerRegex.js, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx
* 고객 회원가입, 아이디찾기, 비밀번호 찾기, input 태그 유효성 검사
*
*
=> KAN-219 feat: 고객 input 유효성 검사

ubun2_fe/src/customer/components/ForgotLoginId/FindLoginId.jsx, ubun2_fe/src/customer/components/ForgotPassword/FindPassword.jsx, ubun2_fe/src/customer/components/ForgotPassword/ResetPassword.jsx, ubun2_fe/src/customer/components/Register/RegisterFirstStep.jsx, ubun2_fe/src/customer/components/Register/RegisterSecondStep.jsx, ubun2_fe/src/customer/components/Register/RegisterThirdStep.jsx, ubun2_fe/src/customer/components/common/Input/InputText.jsx, ubun2_fe/src/customer/components/common/Input/InputTextWithBtn.jsx, ubun2_fe/src/customer/components/common/Regex/registerRegex.js, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx, ubun2_fe/src/member/components/Register/RegisterFirstStep.jsx, ubun2_fe/src/member/components/Register/RegisterSecondStep.jsx, ubun2_fe/src/member/pages/external/ForgotLoginId.jsx, ubun2_fe/src/member/pages/external/ForgotPassword.jsx, ubun2_fe/src/member/pages/external/ResetPassword.jsx
* 회원 회원가입,아이디찾기, 비밀번호찾기, 비밀번호 재설정 유효성 검사
*
*
=> Kan 220 feature/front member iput valid

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/exception/CustomerExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/repository/CustomerRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/controller/FindInfoController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/CheckLoginIdRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/EmailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/FindInfoService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/EmailServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/FindInfoServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/exception/CustomExceptionHandler.java
* loginId 중복체크 및 이메일 인증 발송전 중복이메일 체크
* loginId 중복체크 및 이메일 인증 발송전 중복이메일 체크
*
=> Kan 223 feature/back duplicate check

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_fe/src/customer/api/Order/OrderList/OrderTable/orderTable.js, ubun2_fe/src/customer/api/Order/OrderList/OrderTable/queris.js, ubun2_fe/src/customer/api/Order/PendingOrderList/PendingOrderTable/pendingOrderTable.js, ubun2_fe/src/customer/api/Order/PendingOrderList/PendingOrderTable/queris.js, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableRow.jsx, ubun2_fe/src/customer/components/OrderList/Skeleton/SkeletonOrderTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/Skeleton/SkeletonOrderTableRow.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableFeature.jsx, ubun2_fe/src/customer/components/PendingOrderList/Skeleton/SkeletonPendingOrderTableFeature.jsx, ubun2_fe/src/customer/components/PendingOrderList/Skeleton/SkeletonPendingOrderTableRow.jsx, ubun2_fe/src/customer/components/common/Badge/StatusBadge.jsx, ubun2_fe/src/customer/components/common/Table/UnifiedOrderTableBody.jsx, ubun2_fe/src/customer/components/common/Table/tableIndex.js, ubun2_fe/src/customer/store/OrderTable/orderTableStore.js, ubun2_fe/src/customer/store/PendingOrderTable/pendingOrderTableStore.js
* Kan-22 feature : 주문 정렬 및 스켈레톤 추가
* Kan-22 feature : 주문 정렬 및 스켈레톤 추가
*
=> Kan-22 feature : 주문 정렬 및 스켈레톤 추가

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/UnifiedOrderResponse.java
* 주문 대기 목록 dto 수정
* 주문 대기 목록 dto 수정
*
=> Kan-22 refactor : 주문 대기 목록 dto 수정

ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailInfo.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderPaymentAccount.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderPaymentCard.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SingleOrderProduct.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SubScriptionOrderProduct.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableRow.jsx, ubun2_fe/src/customer/components/PendingOrderList/Skeleton/SkeletonPendingOrderTableRow.jsx, ubun2_fe/src/customer/components/common/Badge/OrderOptionBadge.jsx, ubun2_fe/src/customer/utils/cardFormat.js
* 고객 단 주문 관련 UI 수정
* 고객 단 주문 관련 UI 수정
*
=> Kan-22 refactor : customer order

ubun2_fe/src/customer/api/notification/notification.js, ubun2_fe/src/customer/api/notification/queris.js, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailModal.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableRow.jsx, ubun2_fe/src/customer/components/common/Table/UnifiedOrderTableBody.jsx
* 주문 승인, 거절 시 회원에게 알림 api 데이터셋 변경 및 연동
*
*
=> Kan 225 feature/front pending order notification

ubun2_fe/src/customer/api/Product/ProductList/ProductList/queris.js, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductSaleInfo.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableRow.jsx
=> KAN-227 style: 데이터 포맷변경

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/CustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/response/MypageDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/CustomerService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_fe/src/customer/api/Customer/Mypage/mypage.js, ubun2_fe/src/customer/api/Customer/Mypage/queries.js, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDetail.jsx
* 상점 정보 조회 수정 api
* 상점 정보 조회 수정 api
*
=> KAN-200 feat: 상점 정보 조회 수정 api

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderMemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderDetailProductResponse.java, ubun2_fe/src/member/api/Order/order.js, ubun2_fe/src/member/api/Order/queris.js, ubun2_fe/src/member/components/common/badge/OrderStatusTextBadge.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryCompleted.jsx, ubun2_fe/src/member/components/common/paymentSummary/PaymentSummaryPre.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/MySingleOrderDetail.jsx, ubun2_fe/src/member/store/order/orderItemStore.js
* 주문 관련 오류 해결 및 피드백 반영
* 주문 관련 오류 해결 및 피드백 반영
*
=> Kan-205 refactor : front order UI

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/CalendarController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/CalendarRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/MonthlySummaryResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/CalendarService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryCustom.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java
=> KAN-228 feat: 월간 요약 기능 구현

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/response/MypageDetailResponse.java, ubun2_fe/src/customer/api/Customer/Mypage/mypage.js, ubun2_fe/src/customer/api/Customer/Mypage/queries.js, ubun2_fe/src/customer/components/StoreInfo/StoreDescriptionNotice.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDetail.jsx, ubun2_fe/src/customer/components/common/Input/UpdateInputLabel.jsx
* 상점 정보 조회 수정 API 연동
* 상점 정보 조회 수정 API 연동
* 상점 정보 조회 수정 API 연동 중입니다. 아직 UI적인 수정이 필요합니다
=> KAN-188 feat: 상점 정보 조회 수정 API 연동

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/PaymentPasswordRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderProductRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/CategoryRequest.java, ubun2_fe/src/member/api/Order/queris.js, ubun2_fe/src/member/pages/internal/Order.jsx
* KAN-105 chore: 주문, store validate 수정
* KAN-105 chore: 주문, store validate 수정
*
=> KAN-105 chore: 주문, store validate 수정

ubun2_fe/src/customer/api/Customer/Register/queris.js, ubun2_fe/src/customer/pages/external/ForgotLoginId.jsx, ubun2_fe/src/customer/pages/external/ForgotPassword.jsx, ubun2_fe/src/customer/pages/external/Login.jsx, ubun2_fe/src/customer/pages/external/Register.jsx, ubun2_fe/src/customer/utils/phoneFormat.js, ubun2_fe/src/member/api/Register/queris.js
=> Kan 229 feature/front phone format

ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/memberTable.js, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/queris.js, ubun2_fe/src/customer/api/Product/ProductList/ProductList/productTable.js, ubun2_fe/src/customer/api/Product/ProductList/ProductList/queris.js, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableFeature.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableFeature.jsx, ubun2_fe/src/customer/components/Skeleton/SkeletonTable.jsx, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx
=> Kan 233 feature/front select delete

ubun2_fe/src/customer/api/Register/queris.js, ubun2_fe/src/customer/api/Register/register.js, ubun2_fe/src/customer/api/notification/queris.js, ubun2_fe/src/customer/components/common/Input/AddressInput.jsx, ubun2_fe/src/member/api/Address/addresses.js, ubun2_fe/src/member/api/Address/queries.js, ubun2_fe/src/member/api/Payment/payments.js, ubun2_fe/src/member/api/Payment/queries.js, ubun2_fe/src/member/components/PaymentMethod/MyPagePaymentItem.jsx, ubun2_fe/src/member/components/PaymentMethod/PaymentItem.jsx, ubun2_fe/src/member/components/Register/RegisterFirstStep.jsx, ubun2_fe/src/member/pages/internal/ChoosePayment.jsx, ubun2_fe/src/member/pages/internal/MyPaymentsList.jsx, ubun2_fe/src/member/pages/internal/OrderComplete.jsx, ubun2_fe/src/member/pages/internal/RegisterAddress.jsx, ubun2_fe/src/member/pages/internal/SetPassword.jsx
* 기본 결제수단/ 주소 api 연동
* 기본 결제수단/ 주소 api 연동
*
=> Kan 240 feature/front member

ubun2_fe/src/customer/components/AddressList/AddressTableRow.jsx, ubun2_fe/src/customer/components/AddressList/Skeleton/SkeletonAddressTableRow.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableRow.jsx, ubun2_fe/src/customer/components/MemberList/Skeleton/SkeletonMemberTableRow.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableRow.jsx, ubun2_fe/src/customer/components/OrderList/Skeleton/SkeletonOrderTableRow.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableRow.jsx, ubun2_fe/src/customer/components/PendingOrderList/Skeleton/SkeletonPendingOrderTableRow.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableRow.jsx, ubun2_fe/src/customer/components/ProductList/Skeleton/SkeletonProductTableRow.jsx
* 정렬 시 해당 column에 해당하는 값 text-bold
*
*
=> Kan 232 feature/front sort text

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/cart/service/impl/CartServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/repository/MemberRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx
* 숫자, 날짜 필터링 추가
* 숫자, 날짜 필터링 추가
*
=> Kan-188 feature:숫자, 날짜 필터링 추가

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/financial/institution/repository/BankRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/financial/institution/repository/CardCompanyRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/dto/RegisterPaymentMethodRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/exception/paymentMethod/PaymentMethodExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/service/impl/PaymentMethodServiceImpl.java, ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTable.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTableRow.jsx, ubun2_fe/src/customer/components/common/ToggleButon/ToggleButton.jsx, ubun2_fe/src/customer/store/PaymentMethod/paymentMethodTableStore.js, ubun2_fe/src/customer/utils/accountFormat.js, ubun2_fe/src/member/components/PaymentMethod/AccountForm.jsx, ubun2_fe/src/member/components/PaymentMethod/CardForm.jsx, ubun2_fe/src/member/pages/internal/EditPayment.jsx
* 결제수단 인증기관 인증 추가
* 결제수단 인증기관 인증 추가
*
=> Kan 243 feature/financial institute auth

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/OrderSummaryResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/dto/UnifiedOrderResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/DashboardService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/dashboard/service/impl/DashboardServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/AnnouncementResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/CustomerResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MemberInfoResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/MemberSignUpRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/dto/PaymentPasswordRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/CheckLoginIdRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/EmailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/FindIdRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/FindPasswordRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/ResetPasswordRequest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/ExcelControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/AuthControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/EmailControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/FindInfoControllerTest.java
* dashboard
* auth
* email
* member
* excel
* findinfo
*
*
=> Kan 230 feature/back testcode

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableRow.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx, ubun2_fe/src/customer/components/common/Table/TableHead.jsx, ubun2_fe/src/customer/components/common/Table/tableIndex.js, ubun2_fe/src/index.css
* 주문 결제내역 null 오류 해결 및 검색바 스타일링 수정
* 주문 결제내역 null 오류 해결 및 검색바 스타일링 수정
*
=> Kan-188 feature : front customer store

ubun2_fe/src/customer/api/Address/AddressTable/addressTable.js, ubun2_fe/src/customer/api/Address/AddressTable/queris.js, ubun2_fe/src/customer/api/Customer/MemberList/MemberTable/memberTable.js, ubun2_fe/src/customer/api/Product/ProductList/ProductList/queris.js, ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx, ubun2_fe/src/customer/components/AddressList/AddressTableRow.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx, ubun2_fe/src/customer/components/common/Table/DynamicTableBody.jsx, ubun2_fe/src/customer/components/common/Table/NoDataTable.jsx
=> KAN-253 feat: No Data Table

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_fe/src/customer/api/Customer/Mypage/mypage.js, ubun2_fe/src/customer/components/StoreInfo/StoreDescriptionNotice.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDetail.jsx, ubun2_fe/src/customer/components/common/Input/AddressInput.jsx, ubun2_fe/src/customer/components/common/Input/InputLabel.jsx, ubun2_fe/src/customer/components/common/Input/UpdateInputLabel.jsx, ubun2_fe/src/member/pages/internal/OrderComplete.jsx
=> Kan-188 refactor : customer mypage

ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableFeature.jsx
*  order, product 데이터 없을 시 대체
*
*
=> KAN-253 feat: order, product 데이터 없을 시 대체

ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableFeature.jsx, ubun2_fe/src/member/components/Product/ProductItem.jsx, ubun2_fe/src/member/pages/internal/Product.jsx
=> Kan 254 feature/front nostock

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/ExcelController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/controller/SmsController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/UpdateMemberRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/UpdatePendingMemberRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderMemberController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/InSufficientStockProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/OrderPeriodFilterRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/enums/PeriodType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/exception/OrderExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/SubscriptionOrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductMemberController.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/MemberAddressControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/cart/controller/CartControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/CalendarControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/ExcelControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/SmsControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderMemberControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/MemberPaymentMethodControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductMemberControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/EmailControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/FindInfoControllerTest.java
* 주문 기간별 조회
* 재고부족 메시지 전송
* 주문 기간별 조회
* 재고부족 메시지 전송
*
=> Kan 255 feature/back order

ubun2_fe/src/customer/api/Product/ProductList/ProductList/queris.js, ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx, ubun2_fe/src/customer/components/AddressList/Skeleton/SkeletonAddressTableFeature.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableFeature.jsx, ubun2_fe/src/customer/components/MemberList/Skeleton/SkeletonMemberTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/Skeleton/SkeletonOrderTableFeature.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableFeature.jsx, ubun2_fe/src/customer/components/PendingOrderList/Skeleton/SkeletonPendingOrderTableFeature.jsx, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductDetailModal.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableFeature.jsx, ubun2_fe/src/customer/components/ProductList/Skeleton/SkeletonProductTableFeature.jsx, ubun2_fe/src/customer/components/common/SearchBar/SearchBarWithDrop.jsx, ubun2_fe/src/customer/components/common/Table/DynamicTableBody.jsx, ubun2_fe/src/customer/components/common/Table/NoDataTable.jsx, ubun2_fe/src/customer/store/Address/addressTableStore.js, ubun2_fe/src/customer/store/OrderTable/orderTableStore.js, ubun2_fe/src/customer/store/PendingOrderTable/pendingOrderTableStore.js, ubun2_fe/src/customer/store/ProductTable/productTableStore.js, ubun2_fe/src/customer/utils/CreateSearchResult.jsx, ubun2_fe/src/customer/utils/createSearchResult.js
=> Kan 257 feature/front searchresult

ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/AddressList/AddressTableFeature.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableFeature.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableFeature.jsx
=> KAN-257 feat: 검색결과 없을 시 처리

ubun2_fe/src/member/api/Order/order.js, ubun2_fe/src/member/api/Order/queris.js, ubun2_fe/src/member/pages/internal/MyOrdersList.jsx, ubun2_fe/src/member/pages/internal/MyPage.jsx, ubun2_fe/src/member/pages/internal/MySingleOrderDetail.jsx, ubun2_fe/src/member/pages/internal/MySubscriptionOrderDetail.jsx
* 기간별 필터링 기능 추가
* 기간별 필터링 기능 추가
*
=> Kan-124 feature:기간별 필터링 기능 추가

ubun2_fe/package-lock.json, ubun2_fe/package.json, ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressMap.jsx, ubun2_fe/src/customer/components/AddressList/MemberAddressTable/MemberAddressTable.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardIndex.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardPieChart.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardStats.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardTopBar.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonAreaChart.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonDashboardIndex.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonDashboardStats.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonDashboardTopBar.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonLineChart.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonPieChart.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonRecentOrders.jsx, ubun2_fe/src/customer/components/Dashboard/Skeleton/SkeletonSidoMap.jsx, ubun2_fe/src/customer/components/PaymentMethodList/MemberPaymentMethodModal.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodAccount.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodCard.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTable.jsx, ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodTableRow.jsx, ubun2_fe/src/customer/utils/accountFormat.js
* 대시보드 스켈레톤 처리, 마스킹 처리
* 대시보드 스켈레톤 처리, 마스킹 처리
* 
=> Kan 200 refactor/front dashboard UI

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/OrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/SubscriptionOrderService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/SubscriptionOrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/AccountPaymentRepository.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/paymentmethod/repository/CardPaymentRepository.java, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx
* 주문 데이출력 오류 수정
*주문 데이출력 오류 수정
*
=> KAN-269 fix: 주문 데이출력 오류 수정

ubun2_fe/src/customer/components/common/Badge/StatusBadge.jsx
=> KAN-269 fix: badge 추가

ubun2_fe/src/customer/components/AddressList/AddressTable.jsx, ubun2_fe/src/customer/components/AddressList/AddressTableRow.jsx, ubun2_fe/src/customer/components/MemberList/MemberRegisterModal/MemberRegisterModal.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableRow.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailInfo.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SubScriptionOrderProduct.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableRow.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableRow.jsx, ubun2_fe/src/customer/components/common/Badge/StatusBadge.jsx, ubun2_fe/src/customer/components/common/Table/DynamicTableBody.jsx, ubun2_fe/src/customer/components/common/Table/TableBody.jsx, ubun2_fe/src/customer/components/common/Table/UnifiedOrderTableBody.jsx
=> Kan 271 feature/front norow

ubun2_fe/src/customer/components/MemberList/MemberInfo.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailModal.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableRow.jsx, ubun2_fe/src/customer/components/common/Table/TableHead.jsx, ubun2_fe/src/member/components/Product/SelectOrderTypeModal.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx
=> Kan-124 fix:UI 수정사항 반영

ubun2_fe/package-lock.json, ubun2_fe/package.json, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTableFeature.jsx, ubun2_fe/src/customer/components/common/Modal/AlertConfirmModal.jsx, ubun2_fe/src/customer/components/common/Modal/CheckConfirmModal.jsx, ubun2_fe/src/customer/components/common/Modal/DeleteConfirmModal.jsx, ubun2_fe/src/customer/components/common/Modal/ModalStyle.js, ubun2_fe/src/customer/layouts/Layout.jsx, ubun2_fe/src/customer/store/Modal/deleteConfirmStore.js
=> KAN-273 feat: 체크, 삭제, 경고 모달

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/event/CustomerNoStockAlarmEvent.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/event/NoStockEvent.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/event/OrderCreatedEvent.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/event/SubCycleCompletedEvent.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/event/SubscribeAlarmEvent.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/event/UnSubscribeAlarmEvent.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/listener/AlarmEventListener.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/service/impl/CustomerServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/member/service/impl/MemberServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/SubscriptionOrderServiceImpl.java, ubun2_fe/src/customer/components/common/Table/tableIndex.js
*  event driven- alarm 기능 분리
* event driven- alarm 기능 분리
*
=> KAN-275 feat: event driven- alarm 기능 분리

ubun2_be/.gitignore, ubun2_be/build.gradle, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/AddressControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/controller/MemberAddressControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/address/repository/AddressRepositoryTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/cart/controller/CartControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/CalendarControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/CustomerControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/ExcelControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/customer/controller/SmsControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/dashboard/controller/DashboardControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/member/controller/MemberControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderCustomerControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/order/controller/OrderMemberControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/MemberPaymentMethodControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/paymentmethod/controller/PaymentMethodControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductMemberControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/product/repository/ProductRepositoryTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImplTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/AuthControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/EmailControllerTest.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/global/auth/controller/FindInfoControllerTest.java
=> KAN-230 test: 테스트 코드 수정

ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/customer/components/common/Input/AddressInput.jsx
* 고객 상점 정보 관련 수정
* 고객 상점 정보 관련 수정
*
=> KAN-188 refactor: 고객 상점 정보 관련 수정

ubun2_fe/src/customer/components/StoreInfo/StoreDescriptionNotice.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDetail.jsx, ubun2_fe/src/member/components/common/badge/OrderStatusBadge.jsx, ubun2_fe/src/member/components/common/badge/OrderStatusTextBadge.jsx
* 회원 UI 수정 및 뱃지 수정
* 회원 UI 수정 및 뱃지 수정
*
=> Kan-188 refactor : 회원 UI 수정 및 뱃지 수정

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/dto/EmailRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/EmailServiceImpl.java, ubun2_fe/src/customer/api/Register/queris.js, ubun2_fe/src/customer/components/ForgotLoginId/FindLoginId.jsx, ubun2_fe/src/customer/components/ForgotPassword/FindPassword.jsx, ubun2_fe/src/customer/components/MemberList/MemberTable/MemberTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableRow.jsx, ubun2_fe/src/customer/components/Register/RegisterSecondStep.jsx, ubun2_fe/src/customer/components/common/Badge/ProductOptionBadge.jsx, ubun2_fe/src/customer/components/common/Table/TableBody.jsx, ubun2_fe/src/customer/store/Modal/deleteConfirmStore.js, ubun2_fe/src/member/components/Register/RegisterFirstStep.jsx, ubun2_fe/src/member/components/notification/NotificationItem.jsx, ubun2_fe/src/member/pages/external/ForgotLoginId.jsx, ubun2_fe/src/member/pages/external/ForgotPassword.jsx
=> Kan 277 feature/front fixemail auth

ubun2_fe/public/firebase-messaging-sw.js, ubun2_fe/src/customer/api/Customer/MemberList/MemberModal/queris.js, ubun2_fe/src/customer/utils/CreateSearchResult.jsx
=> KAN-278 feat: 검색결과 단위 등록

ubun2_fe/src/customer/api/Order/OrderList/OrderTable/orderTable.js, ubun2_fe/src/customer/api/Order/OrderList/OrderTable/queris.js, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailInfo.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SubScriptionOrderProduct.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTable.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/OrderTable/OrderTableRow.jsx, ubun2_fe/src/customer/components/OrderList/Skeleton/SkeletonOrderTableFeature.jsx, ubun2_fe/src/customer/components/OrderList/Skeleton/SkeletonOrderTableRow.jsx, ubun2_fe/src/customer/components/OrderList/orderStatusOption.js, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableFeature.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableRow.jsx, ubun2_fe/src/customer/components/PendingOrderList/Skeleton/SkeletonPendingOrderTableFeature.jsx, ubun2_fe/src/customer/components/PendingOrderList/Skeleton/SkeletonPendingOrderTableRow.jsx, ubun2_fe/src/customer/components/Skeleton/SkeletonTable.jsx, ubun2_fe/src/customer/components/Skeleton/SkeletonTableHead.jsx, ubun2_fe/src/customer/components/common/Badge/StatusBadge.jsx, ubun2_fe/src/customer/components/common/Dropdown/Dropdown.jsx, ubun2_fe/src/customer/components/common/Table/NoSelectTableHead.jsx, ubun2_fe/src/customer/components/common/Table/TableHead.jsx, ubun2_fe/src/customer/components/common/Table/tableIndex.js, ubun2_fe/src/customer/store/OrderTable/orderTableStore.js, ubun2_fe/src/customer/utils/addressFormat.js, ubun2_fe/tailwind.config.js
* 회원 주문 페이지에서의 피드백 반영 및 필터링 기능 추가
* 회원 주문 페이지에서의 피드백 반영 및 필터링 기능 추가
*
=> Kan-22 refactor : 회원 주문 페이지

ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryTest.java
* order repository 테스트코드
*order repository 테스트코드
*
=> KAN-279 test: order repository

ubun2_fe/src/member/components/Cart/cartList/CartStore.jsx, ubun2_fe/src/member/components/Order/Order/OrderDeliveryInfo.jsx, ubun2_fe/src/member/components/Product/SelectQuantityModal.jsx, ubun2_fe/src/member/components/common/button/QuantityButton.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemEditable.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/OrderComplete.jsx, ubun2_fe/src/member/pages/internal/Product.jsx, ubun2_fe/src/member/store/order/orderItemStore.js
* 장바구니 재고 관련 수정 및 기능 추가
* 장바구니 재고 관련 수정 및 기능 추가
*
=> Kan-205 refactor : 장바구니 재고 관련 수정 및 기능 추가

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/dto/SubscriptionOrderProductResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/service/impl/OrderServiceImpl.java, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/member/components/Order/OrderMypage/OrderList.jsx, ubun2_fe/src/member/components/common/badge/OrderStatusBadge.jsx, ubun2_fe/src/member/pages/internal/MySingleOrderDetail.jsx, ubun2_fe/src/member/pages/internal/MySubscriptionOrderDetail.jsx
* 회원 마이페이지 주문 분기 처리
* 회원 마이페이지 주문 분기 처리
*
=> Kan-280 feature : 회원 마이페이지 주문 분기 처리

ubun2_fe/src/customer/api/Product/ProductList/ProductList/productTable.js, ubun2_fe/src/customer/api/Product/ProductList/ProductList/queris.js, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ImageWithOverlay.jsx, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductDetailModal.jsx, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductImageCard.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductInsertlModal.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTable.jsx
* 상품 상세정보 이미지 추가 UI
* 상품 상세정보 이미지 추가 UI
*
=> KAN-274 feat: 상품 상세정보 이미지 추가 UI

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/service/AlarmServiceImpl.java, ubun2_be/src/test/java/kr/or/kosa/ubun2_be/domain/alarm/controller/AlarmControllerTest.java, ubun2_fe/src/customer/api/notification/notification.js, ubun2_fe/src/customer/api/notification/queris.js, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTableRow.jsx, ubun2_fe/src/customer/components/common/Table/UnifiedOrderTableBody.jsx, ubun2_fe/src/member/components/notification/NotificationItem.jsx
=> Kan 285 feature/front alramfix

ubun2_fe/src/customer/api/Customer/Register/queris.js, ubun2_fe/src/customer/components/MemberList/MemberInsertModal/MemberInsertModal.jsx, ubun2_fe/src/customer/components/Register/RegisterThirdStep.jsx, ubun2_fe/src/customer/components/common/Input/InputText.jsx, ubun2_fe/src/customer/components/common/Input/InputTextWithBtn.jsx
=> KAN-286 feat: 고객 주소 api 연동

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/alarm/listener/AlarmEventListener.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/controller/ProductCustomerController.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/entity/Product.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/ProductService.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java, ubun2_fe/src/customer/api/Product/ProductList/ProductList/productTable.js, ubun2_fe/src/customer/api/Product/ProductList/ProductList/queris.js, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductCategory.jsx, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductDetailModal.jsx, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductImageCard.jsx, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductSaleInfo.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductInsertlModal.jsx, ubun2_fe/src/customer/components/ProductList/ProductTable/ProductTableRow.jsx
=> Kan 281 feature/back product

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/entity/Product.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java, ubun2_fe/src/customer/components/ProductList/ProductDetailModal/ProductDetailModal.jsx
=> KAN-281 fix: 상세 설정 변경

ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardPieChart.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/DashboardStats.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrders.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/RecentOrdersTable/RecentOrdersTableRow.jsx, ubun2_fe/src/customer/components/Dashboard/DashboardItem/SidoMap.jsx, ubun2_fe/src/customer/components/common/Table/DashBoardTableHeadCell.jsx, ubun2_fe/src/customer/components/common/Table/DashboardTableHead.jsx, ubun2_fe/src/member/components/PaymentMethod/CreditCard.jsx, ubun2_fe/src/member/components/Product/category.js
=> Kan 288 hotfix

ubun2_fe/src/Swagger.jsx
=> KAN-281 refactor: 링크 변경

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/config/SecurityConfig.java
=> KAN-281 refactor: securityconfig 수정

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/dto/ProductDetailResponse.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/product/service/impl/ProductServiceImpl.java, ubun2_fe/src/member/components/common/accordion/AccordionBody.jsx, ubun2_fe/src/member/pages/internal/Product.jsx
=> KAN-288 feat: 상점 정보 디테일

ubun2_fe/src/App.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/OrderDetailModal.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SingleOrderProduct.jsx, ubun2_fe/src/customer/components/OrderList/OrderDetailModal/SubScriptionOrderProduct.jsx, ubun2_fe/src/customer/components/PendingOrderList/PendingOrderTable/PendingOrderTable.jsx, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx, ubun2_fe/src/customer/components/common/Loader/GlobalLoader.jsx, ubun2_fe/src/index.css, ubun2_fe/src/member/components/Cart/cartList/CartSingleOrder.jsx, ubun2_fe/src/member/components/Cart/cartList/CartStore.jsx, ubun2_fe/src/member/components/Cart/cartList/CartSubscriptionOrder.jsx, ubun2_fe/src/member/components/Order/Order/OrderStore.jsx, ubun2_fe/src/member/components/Order/Order/SingleOrder.jsx, ubun2_fe/src/member/components/Order/Order/SubscriptionOrder.jsx, ubun2_fe/src/member/components/Order/OrderMypage/OrderList.jsx, ubun2_fe/src/member/components/Order/OrderMypage/SingleOrderList.jsx, ubun2_fe/src/member/components/Order/OrderMypage/SubscriptionOrderList.jsx, ubun2_fe/src/member/components/Order/OrderMypage/UserInfo.jsx, ubun2_fe/src/member/components/OrderComplete/OrderCompleteStore.jsx, ubun2_fe/src/member/components/common/addressSummary/AddressSummary.jsx, ubun2_fe/src/member/components/common/productItem/OrderItemList.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemReadOnly.jsx, ubun2_fe/src/member/pages/internal/MyOrdersList.jsx
=> Kan-287 feature : front UI style

ubun2_fe/src/customer/components/PaymentMethodList/PaymentMethodAccount.jsx, ubun2_fe/src/member/pages/internal/ChoosePayment.jsx, ubun2_fe/src/member/pages/internal/SetPassword.jsx
* 결제 비밀번호 첫 설정 후 결제 에러해결
* 결제 비밀번호 첫 설정 후 결제 에러해결
*
=> Kan 288 fix/hotfix payment password

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/customer/dto/request/SignupRequest.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/exception/AuthExceptionType.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/EmailServiceImpl.java
=> Kan 281 feature/back

ubun2_fe/src/App.jsx, ubun2_fe/src/member/components/Order/OrderMypage/SingleOrderList.jsx, ubun2_fe/src/member/components/Order/OrderMypage/SubscriptionOrderList.jsx, ubun2_fe/src/member/components/common/productItem/OrderItemList.jsx, ubun2_fe/src/member/components/common/productItem/ProductItemReadOnly.jsx, ubun2_fe/src/member/components/common/productItem/SubscriptionProductItemEditable.jsx, ubun2_fe/src/member/pages/internal/Cart.jsx, ubun2_fe/src/member/pages/internal/MySingleOrderDetail.jsx, ubun2_fe/src/member/pages/internal/MySubscriptionOrderDetail.jsx, ubun2_fe/src/member/pages/internal/OrderComplete.jsx, ubun2_fe/src/member/pages/internal/Store.jsx
=> KAN-287 refactor : loading 수정

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java
* 대시보드 topselling 고객과 관련된 상품만 조회되게 변경
*대시보드 topselling 고객과 관련된 상품만 조회되게 변경
*
=> KAN-288 fix : 대시보드 topselling 고객과 관련된 상품만 조회되게 변경

ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/OrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/domain/order/repository/SubscriptionOrderRepositoryImpl.java, ubun2_be/src/main/java/kr/or/kosa/ubun2_be/global/auth/service/impl/EmailServiceImpl.java
=> KAN-281 fix: left join -> join 변경

ubun2_fe/src/customer/components/Login/LandingIntro.jsx, ubun2_fe/src/customer/layouts/ExternalPageLayout.jsx, ubun2_fe/tailwind.config.js
=> KAN-288 hotfix

ubun2_fe/src/customer/components/Login/LandingIntro.jsx, ubun2_fe/src/index.css
=> KAN-288 style: 스타일변경

ubun2_fe/src/customer/api/notification/queris.js, ubun2_fe/src/customer/components/StoreInfo/StoreInfoDashBoard.jsx
=> KAN-288 fix: 그룹 알림 링크 변경
